dependencies:
  - nbserverproxy
  - bokeh::bokeh
  - pyviz::panel
  - pandas
  - numpy
  - hvplot
  - panel
  - qgrid
  - jupyterlab_dash
  - holoviews
  - markupsafe
  - plotly.express
packages:
  - jupyter-panel-proxy
